 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/project/phase/milestones", type: :request do
  
  # Project::Phase::Milestone. As you add validations to Project::Phase::Milestone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Project::Phase::Milestone.create! valid_attributes
      get project_phase_milestones_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      milestone = Project::Phase::Milestone.create! valid_attributes
      get project_phase_milestone_url(project_phase_milestone)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_project_phase_milestone_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      milestone = Project::Phase::Milestone.create! valid_attributes
      get edit_project_phase_milestone_url(project_phase_milestone)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Project::Phase::Milestone" do
        expect {
          post project_phase_milestones_url, params: { project/phase_milestone: valid_attributes }
        }.to change(Project::Phase::Milestone, :count).by(1)
      end

      it "redirects to the created project/phase_milestone" do
        post project_phase_milestones_url, params: { project/phase_milestone: valid_attributes }
        expect(response).to redirect_to(project_phase_milestone_url(@project_phase_milestone))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Project::Phase::Milestone" do
        expect {
          post project_phase_milestones_url, params: { project/phase_milestone: invalid_attributes }
        }.to change(Project::Phase::Milestone, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post project_phase_milestones_url, params: { project/phase_milestone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project/phase_milestone" do
        milestone = Project::Phase::Milestone.create! valid_attributes
        patch project_phase_milestone_url(project_phase_milestone), params: { project_phase_milestone: new_attributes }
        milestone.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the project/phase_milestone" do
        milestone = Project::Phase::Milestone.create! valid_attributes
        patch project_phase_milestone_url(project_phase_milestone), params: { project_phase_milestone: new_attributes }
        milestone.reload
        expect(response).to redirect_to(project_phase_milestone_url(milestone))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        milestone = Project::Phase::Milestone.create! valid_attributes
        patch project_phase_milestone_url(project_phase_milestone), params: { project_phase_milestone: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested project/phase_milestone" do
      milestone = Project::Phase::Milestone.create! valid_attributes
      expect {
        delete project_phase_milestone_url(project_phase_milestone)
      }.to change(Project::Phase::Milestone, :count).by(-1)
    end

    it "redirects to the project_phase_milestones list" do
      milestone = Project::Phase::Milestone.create! valid_attributes
      delete project_phase_milestone_url(project_phase_milestone)
      expect(response).to redirect_to(project_phase_milestones_url)
    end
  end
end
