 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user/notes", type: :request do
  
  # User::Note. As you add validations to User::Note, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      User::Note.create! valid_attributes
      get user_notes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      note = User::Note.create! valid_attributes
      get user_note_url(user_note)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_note_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      note = User::Note.create! valid_attributes
      get edit_user_note_url(user_note)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new User::Note" do
        expect {
          post user_notes_url, params: { user_note: valid_attributes }
        }.to change(User::Note, :count).by(1)
      end

      it "redirects to the created user_note" do
        post user_notes_url, params: { user_note: valid_attributes }
        expect(response).to redirect_to(user_note_url(@user_note))
      end
    end

    context "with invalid parameters" do
      it "does not create a new User::Note" do
        expect {
          post user_notes_url, params: { user_note: invalid_attributes }
        }.to change(User::Note, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post user_notes_url, params: { user_note: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_note" do
        note = User::Note.create! valid_attributes
        patch user_note_url(user_note), params: { user_note: new_attributes }
        note.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_note" do
        note = User::Note.create! valid_attributes
        patch user_note_url(user_note), params: { user_note: new_attributes }
        note.reload
        expect(response).to redirect_to(user_note_url(note))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        note = User::Note.create! valid_attributes
        patch user_note_url(user_note), params: { user_note: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_note" do
      note = User::Note.create! valid_attributes
      expect {
        delete user_note_url(user_note)
      }.to change(User::Note, :count).by(-1)
    end

    it "redirects to the user_notes list" do
      note = User::Note.create! valid_attributes
      delete user_note_url(user_note)
      expect(response).to redirect_to(user_notes_url)
    end
  end
end
