 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/project/teams", type: :request do
  
  # Project::Team. As you add validations to Project::Team, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Project::Team.create! valid_attributes
      get project_teams_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      team = Project::Team.create! valid_attributes
      get project_team_url(project_team)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_project_team_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      team = Project::Team.create! valid_attributes
      get edit_project_team_url(project_team)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Project::Team" do
        expect {
          post project_teams_url, params: { project_team: valid_attributes }
        }.to change(Project::Team, :count).by(1)
      end

      it "redirects to the created project_team" do
        post project_teams_url, params: { project_team: valid_attributes }
        expect(response).to redirect_to(project_team_url(@project_team))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Project::Team" do
        expect {
          post project_teams_url, params: { project_team: invalid_attributes }
        }.to change(Project::Team, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post project_teams_url, params: { project_team: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project_team" do
        team = Project::Team.create! valid_attributes
        patch project_team_url(project_team), params: { project_team: new_attributes }
        team.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the project_team" do
        team = Project::Team.create! valid_attributes
        patch project_team_url(project_team), params: { project_team: new_attributes }
        team.reload
        expect(response).to redirect_to(project_team_url(team))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        team = Project::Team.create! valid_attributes
        patch project_team_url(project_team), params: { project_team: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested project_team" do
      team = Project::Team.create! valid_attributes
      expect {
        delete project_team_url(project_team)
      }.to change(Project::Team, :count).by(-1)
    end

    it "redirects to the project_teams list" do
      team = Project::Team.create! valid_attributes
      delete project_team_url(project_team)
      expect(response).to redirect_to(project_teams_url)
    end
  end
end
